# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('E', 'employee'), ('C', 'customer')], default='', max_length=1),
        ),
    ]
