# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_person_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('E', 'employee'), ('C', 'customer'), ('U', 'unknown')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
