# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonecalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbers',
            name='description',
            field=models.CharField(default='None', max_length=60),
        ),
        migrations.AddField(
            model_name='phonenumbers',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
